export const STRINGS = {
    paymentOptions:'Payment Options',
    preferredPayment: 'Preferred Payment',
    pay: 'PAY',
    paytm: 'Paytm',
    creditAndDebitCard: 'Credit & Debit Cards',
    morePaymentoptions:'More Payment Options',
    wallets:'Wallets',
    upi:'UPI',
    netBanking: 'Net Banking',
    others: 'Others',
    cardNumber: 'Card Number',
    validThroughMMYY: 'Valid Through (MM/YY)',
    cvv: 'CVV',
    nameOnCard: 'Name On Card',
    mandatoryFields: 'Fields marked with * are mandatory',
    reset: 'Reset',
    proceed: 'Proceed',
    invalidFormat: 'Invalid Format',
    failure: 'Failure',
    success: 'Success',
    processing: 'Processing',
    paymentHasFailed: 'Payment has failed',
    paymentHasSuccess: 'Payment has been made successfully',
    transactionID: 'Transaction ID',
    enterCardDetails: 'Enter Card Details',
}